A large function call parameter or exception catch statement is passed by value
